### ISSUE TITLE
[CRASH] Unhandled Error after saving a service task

### ISSUE THREAD

**Issue by julianweise** [bptlab/gryphon#32]
After adding a task, changing the type to `Service Task` without adding any further information (e.g.: Webservice URL, ...) and pressing the save button, the entire Gryphon service crashes.
The following log was generated:

```
gryphon_1   | Server running on: http://localhost:3000
gryphon_1   | POST /api/fragment/5b23c1707e0383002ec44064 200 30.453 ms - 6225
gryphon_1   | GET /api/fragment/5b23c1707e0383002ec44064/validate 304 35.238 ms - -
gryphon_1   | POST /api/fragment/5b23c1707e0383002ec44064 200 4.323 ms - 6324
gryphon_1   | events.js:167
gryphon_1   |       throw er; // Unhandled 'error' event
gryphon_1   |       ^
gryphon_1   |
gryphon_1   | TypeError: Cannot read property '0' of undefined
gryphon_1   |     at OLCValidator.<anonymous> (/var/gryphon/server_src/helpers/olcvalidator.js:64:75)
gryphon_1   |     at Array.forEach (<anonymous>)
gryphon_1   |     at OLCValidator.<anonymous> (/var/gryphon/server_src/helpers/olcvalidator.js:63:43)
gryphon_1   |     at Array.forEach (<anonymous>)
gryphon_1   |     at OLCValidator.validateDataObjectFlow (/var/gryphon/server_src/helpers/olcvalidator.js:48:41)
gryphon_1   |     at OLCValidator.validateEverything (/var/gryphon/server_src/helpers/olcvalidator.js:30:14)
gryphon_1   |     at GeneralValidator.validateWithSimpleValidator (/var/gryphon/server_src/helpers/validator.js:77:19)
gryphon_1   |     at GeneralValidator.<anonymous> (/var/gryphon/server_src/helpers/validator.js:67:18)
gryphon_1   |     at Array.forEach (<anonymous>)
gryphon_1   |     at GeneralValidator.validateEverything (/var/gryphon/server_src/helpers/validator.js:59:25)
gryphon_1   |     at /var/gryphon/server_src/routes/fragment.js:208:27
gryphon_1   |     at GeneralValidator.<anonymous> (/var/gryphon/server_src/helpers/validator.js:50:13)
gryphon_1   |     at /var/gryphon/node_modules/mongoose/lib/model.js:4208:16
gryphon_1   |     at (anonymous function).call (/var/gryphon/node_modules/mongoose/lib/query.js:3128:7)
gryphon_1   |     at process.nextTick (/var/gryphon/node_modules/mongoose/lib/query.js:2019:28)
gryphon_1   |     at process._tickCallback (internal/process/next_tick.js:61:11)
gryphon_1   | Emitted 'error' event at:
gryphon_1   |     at /var/gryphon/node_modules/mongoose/lib/model.js:4210:13
gryphon_1   |     at (anonymous function).call (/var/gryphon/node_modules/mongoose/lib/query.js:3128:7)
gryphon_1   |     at process.nextTick (/var/gryphon/node_modules/mongoose/lib/query.js:2019:28)
gryphon_1   |     at process._tickCallback (internal/process/next_tick.js:61:11)
bpt-docker-zoo_gryphon_1 exited with code 1
```

**Comment by marhew** [comment]
There is a spurious `bpmn:dataInputAssociation` in the XML serialization of the fragment.
```
<bpmn:serviceTask id=\"Task_0vhxnn8\" name=\"auto\">
    <bpmn:incoming>SequenceFlow_0zwi5vf</bpmn:incoming>
	<bpmn:outgoing>SequenceFlow_1cbp4zm</bpmn:outgoing>
	<bpmn:property name=\"__targetRef_placeholder\" />
	<bpmn:dataInputAssociation />      
	<bpmn:dataInputAssociation id=\"DataInputAssociation_1uzr5y5\">        
		<bpmn:sourceRef>DataObjectReference_1uywzwu</bpmn:sourceRef>        
		<bpmn:targetRef>undefined</bpmn:targetRef>
	</bpmn:dataInputAssociation>
</bpmn:serviceTask>
```
Trying to read the property `sourceRef` of it lets Gyphon crash.
